### ISSUE TITLE
Error on `npm install`

### ISSUE THREAD

**Issue by cristianofromagio** [dwyl/javascript-todo-list-tutorial#26]
I'm using `Windows 10`, `node v12.16.1` and `npm v6.13.4`.

I tried running `npm install` after cloning, and got the following error stack:
 
```
froma@DESKTOP-KGVSTID MINGW64 ~/Development/javascript-todo-list-tutorial (master)
$ npm install
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> pre-commit@1.2.2 install C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\pre-commit
> node install.js


> spawn-sync@1.0.15 postinstall C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\spawn-sync
> node postinstall


> javascript-todo-list-tutorial@1.0.4 postinstall C:\Users\froma\Development\javascript-todo-list-tutorial
> npm test


> javascript-todo-list-tutorial@1.0.4 test C:\Users\froma\Development\javascript-todo-list-tutorial
> istanbul cover tape ./test/*.test.js | tap-spec

No coverage information was collected, exit without writing coverage information
C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\.bin\tape.CMD:1
@ECHO off
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.Module._extensions.<computed> [as .js] (C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at runFn (C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
    at C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\istanbul\lib\util\file-matcher.js:68:16


npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascript-todo-list-tutorial@1.0.4 postinstall: `npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascript-todo-list-tutorial@1.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\froma\AppData\Roaming\npm-cache\_logs\2020-04-27T18_06_17_945Z-debug.log
```

**Comment by nelsonic** [comment]
@cristianofromagio thanks for opening this issue to share your feedback. 💬 
Now that #27 is merged could you please attempt to re-run with NYC instead of istanbul? ♻️ 
Thanks. 🇧🇷 ❤️

**Comment by cristianofromagio** [comment]
@nelsonic Sorry for the delay, `npm install` now runs without errors!
(Windows 10, node v12.16.2, npm 6.14.4)

```
$ npm install
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> pre-commit@1.2.2 install C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\pre-commit
> node install.js


> spawn-sync@1.0.15 postinstall C:\Users\froma\Development\javascript-todo-list-tutorial\node_modules\spawn-sync
> node postinstall


> javascript-todo-list-tutorial@1.0.4 postinstall C:\Users\froma\Development\javascript-todo-list-tutorial
> npm test


> javascript-todo-list-tutorial@1.0.4 test C:\Users\froma\Development\javascript-todo-list-tutorial
> nyc tape ./test/*.test.js | tap-nyc

    JSDOM window.location.href: about:blank
    START window.location.hash:  (empty string)
    START window.history.length: 1
    UPDATED window.history.length: 2
    UPDATED state: { hash: '#/active' }
    UPDATED window.location.hash: #/active
    value: Let's solve our own problem
    value: Let's solve our own problem
    value: Let's solve our own problem
    value: Let's solve our own problem
    value: Let's solve our own problem
    -------------|---------|----------|---------|---------|-------------------
    File         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
    -------------|---------|----------|---------|---------|-------------------
    All files    |     100 |      100 |     100 |     100 |
     elmish.js   |     100 |      100 |     100 |     100 |
     todo-app.js |     100 |      100 |     100 |     100 |
    -------------|---------|----------|---------|---------|-------------------

  total:     138
  passing:   138

  duration:  6.2s

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 494 packages from 289 contributors and audited 495 packages in 40.859s

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by nelsonic** [comment]
@cristianofromagio thanks for confirming. 👍
